-- MySQL Script generated by MySQL Workbench
-- Mon Mar 27 19:42:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Adocao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Adocao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Adocao` DEFAULT CHARACTER SET utf8 ;
USE `Adocao` ;

-- -----------------------------------------------------
-- Table `Adocao`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Adocao`.`Usuario` (
  `IdUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(15) NOT NULL,
  `Cep` VARCHAR(15) NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Numero` VARCHAR(10) NOT NULL DEFAULT 'S/N',
  `Bairro` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`IdUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Adocao`.`Anuncio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Adocao`.`Anuncio` (
  `IdAnuncio` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  `Sexo` CHAR NOT NULL,
  `Idade` VARCHAR(45) NOT NULL DEFAULT 'Indefinido',
  `Castrado` CHAR NOT NULL,
  `Categoria` INT NOT NULL,
  `UsuarioId` INT NOT NULL,
  PRIMARY KEY (`IdAnuncio`, `UsuarioId`),
  INDEX `fk_Anuncio_Usuario_idx` (`UsuarioId` ASC),
  CONSTRAINT `fk_Anuncio_Usuario`
    FOREIGN KEY (`UsuarioId`)
    REFERENCES `Adocao`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Adocao`.`Foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Adocao`.`Foto` (
  `IdFoto` INT NOT NULL AUTO_INCREMENT,
  `Url` VARCHAR(255) NOT NULL,
  `AnuncioId` INT NOT NULL,
  `UsuarioId` INT NOT NULL,
  PRIMARY KEY (`IdFoto`, `AnuncioId`, `UsuarioId`),
  INDEX `fk_Foto_Anuncio1_idx` (`AnuncioId` ASC, `UsuarioId` ASC),
  CONSTRAINT `fk_Foto_Anuncio1`
    FOREIGN KEY (`AnuncioId` , `UsuarioId`)
    REFERENCES `Adocao`.`Anuncio` (`IdAnuncio` , `UsuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Adocao` ;

-- -----------------------------------------------------
-- Placeholder table for view `Adocao`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Adocao`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `Adocao`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Adocao`.`view1`;
USE `Adocao`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
